[package]
name = "handwritten-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bolero = "0.12.0"
bolero-generator = "0.12.0"
criterion = "0.5.1"

[[bench]]
name = "gen_bm"
harness = false